version: "3.9"

services:
  api:
    build: .
    container_name: chatbot_api
    volumes:
      - .:/app
    ports:
      - "8006:8006"
    env_file:
      - .env
    depends_on:
      - db


  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  redis:
      image: redis/redis-stack:latest
      ports:
        - "6380:6379"
      environment:
        - REDIS_ARGS=--requirepass Ditstek12345 --bind 0.0.0.0 --protected-mode yes
      volumes:  
        - redis_data:/data
      healthcheck:
        test: ["CMD", "redis-cli", "-a", "Ditstek12345", "ping"]
        interval: 30s
        timeout: 10s
        retries: 5
      restart: always

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local