version: "3.9"

services:
  api:
    build: .
    container_name: chatbot_api
    volumes:
      - .:/app
    ports:
      - "8006:8006"
    env_file:
      - .env
    depends_on:
      - db

  utility_app:
    build: .
    container_name: chatbot_utility_app
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - api
      - db
    command: ["python", "run_utility.py"]


  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  redis:
      image: redis/redis-stack:latest
      ports:
        - "6379:6379"
      environment:
        - REDIS_ARGS=--requirepass Ditstek12345 --bind 0.0.0.0 --protected-mode yes
      volumes:
        - redis_data:/data
      healthcheck:
        test: ["CMD", "redis-cli", "-a", "Ditstek12345", "ping"]
        interval: 30s
        timeout: 10s
        retries: 5
      restart: always

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb_server
    ports:
      - "8001:8000"  # Map to 8001 to avoid conflicts
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
    volumes:
      - chroma_data:/chroma/chroma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v2/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  chroma_data:
    driver: local