[project]
name = "chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "dotenv>=0.9.9",
    "faiss-cpu>=1.12.0",
    "fastapi>=0.118.2",
    "langchain>=0.3.27",
    "langchain-community===0.3.30",
    "langchain-core>=0.3.79",
    "langchain-openai>=0.3.35",
    "markdown2>=2.5.4",
    "numpy>=2.3.3",
    "openai>=2.3.0",
    "pdfplumber>=0.11.7",
    "playwright>=1.55.0",
    "psycopg2-binary>=2.9.10",
    "pydantic-settings>=2.11.0",
    "pydantic[email]>=2.12.0",
    "redis>=6.4.0",
    "requests>=2.32.5",
    "sentence-transformers==5.1.1",
    "tavily-python>=0.7.12",
    "uvicorn>=0.37.0",
]
[tool.setuptools]
packages = ["app"]
