# UC1 State Machine - Deterministic State Transitions
#
# ARCHITECTURE RULE: The state machine owns ALL transition logic.
# LLM never decides state transitions - only the orchestrator through this machine.
#
# State transitions are deterministic based on:
# - Current state
# - User input type (button click vs free text)
# - Required slots being filled

from dataclasses import dataclass, field
from enum import Enum
from typing import Set, List, Optional, Dict, Literal
from app.logger import get_logger

logger = get_logger("state_machine")


class UC1State(Enum):
    """
    The 8 states of the UC1 conversation flow.
    
    Flow: ENTRY → CAPABILITY_SELECTION → CONTEXT_QUESTION → NAME_CAPTURE 
          → AI_SYNTHESIS → CONSULTATIVE_ALTERNATIVES → RECOMMENDATION → EXIT
    
    Note: Some transitions allow looping (e.g., RECOMMENDATION → CAPABILITY_SELECTION
    via "Continue exploring" CTA).
    """
    ENTRY = "entry"
    CAPABILITY_SELECTION = "capability_selection"
    CONTEXT_QUESTION = "context_question"
    NAME_CAPTURE = "name_capture"
    AI_SYNTHESIS = "ai_synthesis"
    CONSULTATIVE_ALTERNATIVES = "consultative_alternatives"
    RECOMMENDATION = "recommendation"
    EXIT = "exit"


# Input types that the user can provide
InputType = Literal["none", "buttons", "text"]


@dataclass(frozen=True)
class StateConfig:
    """
    Configuration for a single state.
    
    Defines what inputs are valid, what slots are required,
    and what states can follow.
    """
    input_type: InputType  # What kind of input this state expects
    next_states: tuple  # Valid next states (tuple of UC1State)
    required_slots: tuple  # Slots that must be filled to advance (tuple of str)
    retry_limit: int = 3  # Max retries for invalid input before escalation
    system_message_key: Optional[str] = None  # Key to fetch system message for this state


# State configuration - defines the entire state machine
STATE_CONFIGS: Dict[UC1State, StateConfig] = {
    UC1State.ENTRY: StateConfig(
        input_type="none",  # System auto-advances, no user input needed
        next_states=(UC1State.CAPABILITY_SELECTION,),
        required_slots=(),
        system_message_key="entry_message",
    ),
    UC1State.CAPABILITY_SELECTION: StateConfig(
        input_type="buttons",  # User selects from 6 capability buckets
        next_states=(UC1State.CONTEXT_QUESTION,),
        required_slots=("capability_bucket",),
        system_message_key=None,  # Message is derived from entry_message
    ),
    UC1State.CONTEXT_QUESTION: StateConfig(
        input_type="text",  # User provides free-form context answer
        next_states=(UC1State.NAME_CAPTURE,),
        required_slots=("context_signal",),
        system_message_key=None,  # Message comes from bucket.context_question
    ),
    UC1State.NAME_CAPTURE: StateConfig(
        input_type="text",  # User provides their name
        next_states=(UC1State.AI_SYNTHESIS,),
        required_slots=("user_name",),
        system_message_key="name_capture_prompt",
    ),
    UC1State.AI_SYNTHESIS: StateConfig(
        input_type="none",  # System auto-advances after generating synthesis
        next_states=(UC1State.CONSULTATIVE_ALTERNATIVES,),
        required_slots=(),
        system_message_key=None,  # Generated by LLM paraphraser
    ),
    UC1State.CONSULTATIVE_ALTERNATIVES: StateConfig(
        input_type="buttons",  # User selects from 3 alternatives
        next_states=(UC1State.RECOMMENDATION,),
        required_slots=(),  # Selection is informational, not blocking
        system_message_key=None,  # Alternatives come from bucket config
    ),
    UC1State.RECOMMENDATION: StateConfig(
        input_type="buttons",  # User selects from 4 CTAs
        next_states=(UC1State.EXIT, UC1State.CAPABILITY_SELECTION),  # Exit or loop
        required_slots=(),
        system_message_key=None,  # CTAs come from config
    ),
    UC1State.EXIT: StateConfig(
        input_type="none",  # Terminal state
        next_states=(),  # No next states - conversation ends
        required_slots=(),
        system_message_key=None,  # Exit summary generated by LLM
    ),
}


class UC1StateMachine:
    """
    Deterministic state machine for UC1 conversation flow.
    
    OWNERSHIP:
    - This class owns ALL transition logic
    - Orchestrator calls this to determine valid transitions
    - LLM never influences state transitions
    """
    
    def __init__(self):
        self._configs = STATE_CONFIGS
    
    def get_state_config(self, state: UC1State) -> StateConfig:
        """Get configuration for a state."""
        return self._configs[state]
    
    def get_valid_next_states(self, current_state: UC1State) -> tuple:
        """Get valid next states from current state."""
        return self._configs[current_state].next_states
    
    def get_required_slots(self, state: UC1State) -> tuple:
        """Get slots required to advance from this state."""
        return self._configs[state].required_slots
    
    def get_input_type(self, state: UC1State) -> InputType:
        """Get expected input type for a state."""
        return self._configs[state].input_type
    
    def is_terminal(self, state: UC1State) -> bool:
        """Check if state is terminal (no valid next states)."""
        return len(self._configs[state].next_states) == 0
    
    def can_transition(
        self,
        from_state: UC1State,
        to_state: UC1State,
        filled_slots: Set[str],
    ) -> bool:
        """
        Check if transition is valid given current slots.
        
        Args:
            from_state: Current state
            to_state: Proposed next state
            filled_slots: Set of slot names that are currently filled
        
        Returns:
            bool: True if transition is valid
        """
        config = self._configs[from_state]
        
        # Check if to_state is a valid next state
        if to_state not in config.next_states:
            logger.warning(
                f"[StateMachine] Invalid transition: {from_state.value} → {to_state.value} "
                f"(valid: {[s.value for s in config.next_states]})"
            )
            return False
        
        # Check if required slots are filled
        required = set(config.required_slots)
        missing = required - filled_slots
        if missing:
            logger.warning(
                f"[StateMachine] Transition blocked: {from_state.value} → {to_state.value} "
                f"(missing slots: {missing})"
            )
            return False
        
        return True
    
    def get_default_next_state(self, current_state: UC1State) -> Optional[UC1State]:
        """
        Get the default next state (first in the list of valid next states).
        
        Used when there's only one valid next state.
        """
        next_states = self._configs[current_state].next_states
        if next_states:
            return next_states[0]
        return None
    
    def get_next_state_for_cta(
        self,
        current_state: UC1State,
        cta_outcome: str,
    ) -> Optional[UC1State]:
        """
        Determine next state based on CTA outcome.
        
        This is specifically for RECOMMENDATION state where CTAs
        can lead to different next states.
        
        Args:
            current_state: Must be RECOMMENDATION
            cta_outcome: The outcome string from ExitCTA
        
        Returns:
            UC1State: The next state based on CTA, or None if invalid
        """
        if current_state != UC1State.RECOMMENDATION:
            logger.warning(f"[StateMachine] get_next_state_for_cta called from non-RECOMMENDATION state: {current_state.value}")
            return None
        
        # Map CTA outcomes to states
        outcome_map = {
            "UC2": UC1State.EXIT,  # Hand off to UC2 (future)
            "calendar": UC1State.EXIT,  # Schedule call = exit with calendar action
            "loop": UC1State.CAPABILITY_SELECTION,  # Continue exploring = loop back
            "exit": UC1State.EXIT,  # Graceful exit
        }
        
        next_state = outcome_map.get(cta_outcome)
        if next_state is None:
            logger.warning(f"[StateMachine] Unknown CTA outcome: {cta_outcome}")
        
        return next_state
